[package]
name = "radiotap"
version = "1.3.0"
authors = ["Ross MacArthur <macarthur.ross@gmail.com>"]
license = "Apache-2.0/MIT"
description = "A parser for the Radiotap capture format. See http://www.radiotap.org."
keywords = ["radiotap", "packet", "parsing", "wifi"]
readme = "README.md"
homepage = "https://github.com/rossmacarthur/radiotap"
repository = "https://github.com/rossmacarthur/radiotap"

[dependencies]
bitops = "0.1"
byteorder = "1.2"
quick-error = "1.2"

[dev-dependencies]
pcap = "0.7"
